version: "2"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: devicehive-zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:0.10.0.1
    container_name: devicehive-kafka
    ports:
      - "9092:9092"
    depends_on:
      - "zookeeper"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    image: postgres:9.4.4
    container_name: devicehive-postgres
    ports:
      - "5432:5432"

  dh_admin:
    build: ./admin
    image: kgoutsos/devicehive-admin
    container_name: devicehive-admin
    ports:
      - "80:80"
    depends_on:
      - "dh_frontend"
    environment:
      DH_HOST: dh_frontend
      DH_PORT: 8080

  dh_frontend:
    build: ./frontend
    image: kgoutsos/devicehive-frontend
    container_name: devicehive-frontend
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
      - "kafka"
      - "zookeeper"
    environment:
      DH_ZK_ADDRESS: zookeeper
      DH_ZK_PORT: 2181
      DH_KAFKA_ADDRESS: kafka
      DH_KAFKA_PORT: 9092
      DH_POSTGRES_ADDRESS: postgres
      DH_POSTGRES_PORT: 5432
      DH_POSTGRES_USERNAME: "postgres"
      DH_POSTGRES_PASSWORD: "mysecretpassword"
      DH_POSTGRES_DB: "postgres"

  dh_backend:
    build: ./backend
    image: kgoutsos/devicehive-backend
    container_name: devicehive-backend
    depends_on:
      - "postgres"
      - "kafka"
      - "zookeeper"
    environment:
      DH_ZK_ADDRESS: zookeeper
      DH_ZK_PORT: 2181
      DH_KAFKA_ADDRESS: kafka
      DH_KAFKA_PORT: 9092
      DH_POSTGRES_ADDRESS: postgres
      DH_POSTGRES_PORT: 5432
      DH_POSTGRES_USERNAME: "postgres"
      DH_POSTGRES_PASSWORD: "mysecretpassword"
      DH_POSTGRES_DB: "postgres"
